import { join } from "node:path";

import express, { type Express } from "express";
import helmet from "helmet";

import { STATIC_ASSETS_MAX_AGE_S } from "../../shared/constants";

interface HttpAppOptions {
  /** Directory holding the built client, or null in development where Vite serves it. */
  clientDir: string | null;
  /** True where the site is served over https, which on Render means production (§10). */
  secureOrigin: boolean;
}

export function createHttpApp({ clientDir, secureOrigin }: HttpAppOptions): Express {
  const app = express();

  const directives: Record<string, string[] | null> = {
    // Socket.IO polls over HTTP, then upgrades to a WebSocket: both stay on this origin.
    "connect-src": ["'self'"],
    // The client carries no inline style and no external stylesheet: a player colour comes
    // from a class, never from a `style` attribute (docs/design-system.md, §4.2).
    "style-src": ["'self'"],
  };

  if (!secureOrigin) {
    // Helmet upgrades every http request to https by default. Over https that is a safety net;
    // over http it breaks the site outright in Safari, which applies the directive to localhost
    // where Chrome and Firefox make an exception. Every file is then asked for over a TLS the
    // server does not speak, and the page stays blank. `null` is how helmet drops one of its own
    // defaults (docs/architecture.md, §2).
    directives["upgrade-insecure-requests"] = null;
  }

  app.use(helmet({ contentSecurityPolicy: { useDefaults: true, directives } }));

  app.get("/healthz", (_request, response) => {
    response.type("text/plain").send("ok");
  });

  if (clientDir !== null) {
    const indexPath = join(clientDir, "index.html");

    // Names in assets/ carry a hash generated by Vite, so their content never changes and they
    // can be cached for a long time. express takes a duration string; the reference is in seconds.
    app.use(
      "/assets",
      express.static(join(clientDir, "assets"), {
        index: false,
        immutable: true,
        maxAge: `${STATIC_ASSETS_MAX_AGE_S}s`,
      }),
    );

    // Every other static file (fonts, favicon) keeps its name from one version to the next, so it
    // only gets ETag revalidation. index.html is never cached at all.
    app.use(
      express.static(clientDir, {
        index: false,
        setHeaders(response, filePath) {
          if (filePath.endsWith(".html")) {
            response.setHeader("Cache-Control", "no-store");
          }
        },
      }),
    );

    // Routing happens in the browser: anything else returns index.html, never cached so that a
    // deployment cannot keep serving the previous one.
    app.use((request, response, next) => {
      if (request.method !== "GET" && request.method !== "HEAD") {
        next();
        return;
      }

      response.setHeader("Cache-Control", "no-store");
      response.sendFile(indexPath);
    });
  }

  return app;
}
